#!/usr/bin/env ruby

puts "---------------------------------------------------"
puts "oblessd v0.1 -- a throttled Plasma WebSocket server"
puts "created by Samuel Luescher <luescher@media.mit.edu>"
puts "---------------------------------------------------"

require 'rubygems'
require 'em-websocket'

$: << '/opt/oblong/g-speak-64-2/lib64/ruby/'
require 'Pool'
include Plasma

pool = "tcp://gspeak01.media.mit.edu/tags"
host = "0.0.0.0"
port = 8080
debug = false
watch_tags = {}
fps = 50.0
time_samples = []
num_time_samples = 50
frames_sent = 0

send_tags = {}
open_sockets = []

Thread.abort_on_exception = true
t1 = Thread.new do
  puts "Creating Hose to %s" % pool
  h = Hose.new(pool)
  prev_time = Time.now
  loop {
    h.tolast 
    prot = h.next
    next_time = Time.now
    if next_time - prev_time >= 1 / fps
      for socket in open_sockets
        send_tags = {}
        if prot
          for tag in watch_tags[socket]
            if prot.ingests["tags"][tag]
              send_tags[tag] = prot.ingests["tags"][tag]
            end
          end
        end
        socket.send(send_tags.to_json)
      end
      prev_time = next_time
      time_samples.push(Time.now.to_i)
      if time_samples.length > num_time_samples:
        time_samples.shift
      end
      if time_samples.length >= 2 and frames_sent % 10 == 0:
        #puts time_samples.length / (time_samples[time_samples.length - 1] - time_samples[0])
      end
      frames_sent += 1
    end
  }
end

if ARGV.length > 0:
  split = ARGV[0].split(':')
  host = split[0]
  if split.length > 1:
    port = split[1]
  end 
end

puts "Starting oblessd on %s:%i at %i fps" % [host, port, fps]

EventMachine::WebSocket.start(:host => host, :port => port, :debug => debug) do |ws|
  timer = nil
  ws.onopen {
    puts "WebSocket connected"
    open_sockets.push(ws)
    watch_tags[ws] = []
  }
  ws.onclose {
    EM.cancel_timer(timer)
    puts "WebSocket closed"
    open_sockets.delete(ws)
  }
  ws.onerror { |e|
    puts "Error: #{e.message}"
  }
  ws.onmessage { |msg|
    words = msg.split(' ')
    case words[0]
    when 'watch'
      if words.length == 2:
        puts msg
        if not watch_tags.include?(words[1]):
          watch_tags[ws].push(words[1])
        end
      end
    end
  }
end

